version: '3.8'

services:
  app_1:
    container_name: app_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50050:50050"
      - "50051:50051"
    environment:
      - REST_SERVER_PORT=50050
      - GRPC_SERVER_PORT=50051
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=lyceum
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  app_2:
    container_name: app_2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50049:50049"
      - "50052:50052"
    environment:
      - REST_SERVER_PORT=50049
      - GRPC_SERVER_PORT=50052
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=lyceum
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  app_3:
    container_name: app_3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50048:50048"
      - "50053:50053"
    environment:
      - REST_SERVER_PORT=50048
      - GRPC_SERVER_PORT=50053
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=lyceum
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lyceum
    container_name: postgres_container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d lyceum"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
    networks:
      - app_network

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
  
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app_1
      - app_2
      - app_3
    networks:
      - app_network


volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
